from typing import Protocol

from src.core.models import FundingRate, Ticker
from src.core.state import MarketState


class ExchangeConnector(Protocol):
    name: str

    async def get_funding_rates(self) -> dict[str, FundingRate]: ...
    async def get_tickers(self) -> dict[str, Ticker]: ...
    async def get_market_data(self) -> tuple[dict[str, FundingRate], dict[str, Ticker]]: ...
    async def start_stream(self, state: MarketState) -> None: ...
    async def close(self) -> None: ...
